### ISSUE TITLE
Two Bugs when displaying comments + comment suggest change doesn't work

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_comments#116]
**Summary**

There occur two appeareance bugs with the comments plugin and within this the option.

**Steps to reproduce**

I'm using Windows 8.1 and Firefox 75.0

- (1) Go to a line and add several comments, then they overlap. The last one always hides the other ones so that the others can't be edited (The screenshot below was taken from https://pad.systemli.org)
![Pad_Systemli_overlapping_comments](https://user-images.githubusercontent.com/44228345/79210994-e3540900-7e45-11ea-9ea5-20b333e23561.PNG)
- (2) When you go on a comment in the line, the corresponding box shows on the right. When you go with the cursor to the right, it disappears. 
- (3) when "table of contents" and "Chat (and user) always on screen" setting is enabled, table of contents overlaps the comment. Only occurs on https://board.net

**Example**

https://board.net/p/testpad_der_tuuwi
https://pad.systemli.org/p/PostWachstumsDefinition-temp

**What is the expected correct behavior?**

- (1) comments when comments overlap, they should have permanent, untransparent boxes
  - this already happens on board
  - on Systemli for example the comments on the right are transparent and they overlap (see image above)
- (2) the corresponding box on the right should stay when clicking on a comment in the text 
- (3) toc shouldn't overlap comment. It should be shown above ToC when selected.

**Possible fixes**

On sandstorm you can test pads for one hour in the demo version, the have high level functionality with stable plugins, there the comments work fine! I don't know how they did this 

https://sandstorm.io/demo

P.S.: Furthermore, "include suggested change" doesn't work on the board.net instance.

**Comment by JohnMcLear** [comment]
@Oremountainflorian can you replicate on https://video.etherpad.com ?  I think this is an old bug.  If you can replicate there I will re-open.
