### ISSUE TITLE
[question] Why should I use git instead of npm to install this plugin?

### ISSUE THREAD

**Issue by techware01** [ether/ep_comments#123]
At first I installed this plugin via git as descriped in the readme. 
It worked, but npm didn't like a git repo inside node_modules and e.g. it deleted the plugins repo as soon as I installed another plugin.

Thats why I installed it via npm (npm i ep_comments_page) the next time and it works totally fine now.

Is there any reason why I should use git instead of npm to install this plugin?

**Comment by JohnMcLear** [comment]
Yeah git repos inside node modules doesn't play well..

**Comment by techware01** [comment]
Then I would suggest to update the installation instructions in the readme file ...

**Comment by JohnMcLear** [comment]
Done and lol I see why not, it used to depend on ep_page_view, but it doesn't any more...   I removed it completely.

**Comment by techware01** [comment]
Thank you very much! That's good news :)
