### ISSUE TITLE
Hotfix, `setYofComments` is undefined

### ISSUE THREAD

**Issue by HMarzban** [ether/ep_comments#127]
https://github.com/ether/ep_comments/blob/848889ffc0e94d75d5dfda26844b8853ed929cc0/static/js/index.js#L1222

Some times (**most of the time when the system is under heavy load**) `aceEditEvent` hook happened sooner than `postAceInit` hook, so in this case, `ep_comments` is not yet in the plugin list.

Thus we need another condition to check if `pad.plugins.ep_comments_page` exist then make call `setYofComments()`

```js
if(context.callstack.docTextChanged) 
   pad.plugins.ep_comments_page.setYofComments();

// to

if(context.callstack.docTextChanged && pad.plugins.ep_comments_page)
  pad.plugins.ep_comments_page.setYofComments();

```
![image](https://user-images.githubusercontent.com/20157508/84255194-857f2d00-ab27-11ea-9ace-3b5e52e58169.png)
![image](https://user-images.githubusercontent.com/20157508/84255196-857f2d00-ab27-11ea-8e29-697e2dcedad4.png)

**Comment by samirsayyad** [comment]
+1

**Comment by JohnMcLear** [comment]
Can you please include test coverage?

**Comment by Chostakovitch** [comment]
I also have the same issue, hundreds of time for the last few days in the logs.

**Comment by JohnMcLear** [comment]
Would merge a PR (ideally with test coverage) if one landed.

**Comment by crablab** [comment]
It's not clear to me where you have test cases for this file, and how you would like to test this. If you can provide more context on that I'll have a look. 

Otherwise, I have a PR for the fix.
