### ISSUE TITLE
[Bug] Copying text to clipboard doesn't work when text contains comment

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_comments#128]
## System

Etherpad: 1.8.4 
OS: Windows 10/8.1
ep_comments: 0.1.5

## Problem description

When there is a comment in selected text, it isn't possible to copy text to clipboard and paste it afterwards. Problem occurs on Firefox 76.1 and Chrome 83 but doesn't occur on Microsoft Edge Microsoft Edge 42.17134.1098.0.

**Comment by JohnMcLear** [comment]
Unable to replicate.

**Comment by lfrancke** [comment]
Just to add a single data point: I have the same issue.

I can copy & paste everything without issues, but as soon as I try to copy something that has a comment it does not work (nothing is copied)

- Linux
- Firefox (114.0.2) & Chrome (114)

I've been invited to participate in an Etherpad and I can't find a way to find the versions of either the plugin or Etherpad itself.

**Comment by KamilBaczkowski** [comment]
I also have this issue, here is a video:
[Screencast from 2024-02-18 14-55-54.webm](https://github.com/ether/ep_comments_page/assets/41474169/c9602276-74e3-4611-a3cd-2dcb6fa0a2c3)
and here is a pad where it can be easily reproduced: https://pad.kavela.ch/p/ep_comments_page_copy_bug
