### ISSUE TITLE
[bug]had error when you are commenting on words after other one delete those words

### ISSUE THREAD

**Issue by wwwjason1994** [ether/ep_comments#133]
Case 1: would commented other word
case 2: would alert error message

**Comment by JohnMcLear** [comment]
1. I guess not erroring would be a good start.  Use try catch might be required.
1. Notify comment window that contents has changed so to ensure selection and comment is accurate based on change. OR just disable comment window submission if content changes but that's gotta be so counterproductive.

**Comment by JohnMcLear** [comment]
STR:

Create pad
Put content "hey" at bottom of pad
in another browser, highlight hey, start writing a comment, don't submit it
in original browser delete "hey".

2nd browser will hang 👎

**Comment by JohnMcLear** [comment]
Fixed in https://github.com/ether/ep_comments/commit/86e89a3b44676bb7b6b0d2e80abc28a2c9674c69
