### ISSUE TITLE
Changing the language does not change the relative time strings

### ISSUE THREAD

**Issue by rhansen** [ether/ep_comments#155]
If you change the language, relative time strings such as "1 minute ago" do not update. You have to reload the page to see the translated strings.

The tests are supposed to test for this but they don't due to [timeFormat.js line 177](https://github.com/ether/ep_comments/blob/0cf037f4e52dfa13620f4712e8d466d5ea4d4109/static/tests/frontend/specs/timeFormat.js#L177).

**Comment by JohnMcLear** [comment]
@ilmartyrk
