### ISSUE TITLE
Work smoothly on mobile devices

### ISSUE THREAD

**Issue by lpagliari** [ether/ep_comments#67]
I was testing ep_comments on mobile devices (iPad and iPhone, for now) and noticed some functionalites were not working properly there (clicking to open/close the comment modal, adding comments, etc).

I'm planning to work on this, so wanted to know if anyone has any concerns about it. It seems that http://jquerymobile.com/ could help us, but to be honest I just gave a fast look on it.

Concerns about this? Or about using jQuery Mobile?

I'll work on a separated branch this time, to avoid conflicts if this takes too long to finish.

**Comment by JohnMcLear** [comment]
Happy for you to fix but plz avoid jqm.  It's really bloated and will req another http request that I want to avoid
----- Reply message -----

**Comment by niallmurphy-ie** [comment]
Hi lpagliari, did you ever make any progress on adding a comment to an existing comment on mobile?

I have a system built already with Annotator JS but would love to jump completely over to etherpad.

**Comment by lpagliari** [comment]
No, I've started to work on it but did not finished, and later mobile devices were not our top priority on the project.

**Comment by DanielBickley** [comment]
Hi @lpagliari, I know you worked on the comment icon portion, and I've run into an issue with the comment icon itself where it is not triggered on a tablet (i.e. there is no way to open a comment dialogue via icon on an iPad). I've tried converting the 'click' events in ep_comments_page/static/js/index.js to 'touchstart click' and I see you already have them that way in ep_comments_page/static/js/commentIcons.js. Have you run up against this?

Maybe i'll convert them to 'touchend click' and see if that helps. I'll let you know. Thanks!

**Comment by lpagliari** [comment]
No, @DanielBickley. Initially I was developing a plugin that would display a popover every time user selected a text (and that would listen to touchstart), but I didn't have time to finish it before moving to another direction.

Your idea of adding touchstart to click seems correct to me, I believe it would enable adding comments on iOS.

**Comment by DanielBickley** [comment]
@lpagliari thanks for your help. As it turns out, the clicks were being respected on the iPad, only the measurements on the text area width were off ~80px for me (i.e., the comment block on the right was actually covering the icons making them unclickable). I adjusted widths in the media query a bit and iPad is working.

**Comment by lpagliari** [comment]
Awesome!

**Comment by JohnMcLear** [comment]
I think this is resolved but if not please comment here and I will re-open.
