### ISSUE TITLE
UX: No submit button when replying to comments

### ISSUE THREAD

**Issue by rugk** [ether/ep_comments#92]
There is no submit or comment button when replying to comments. This is bad as it is no good UX to require the user to press enter.

E.g. this is the "workflow" when _adding a suggestion_ (so not adding a actual comment) to a user who commented on a line:
1. Hover over the comment
2. Click on "Suggest changes"
3. Enter the suggestion
4. Click bad into the field for entering a comment (bad UX!, few users would know that they have to do this)
(5. Read the title which says "Press enter")
6. Press enter.

That's not user-friendly.
Just showing a button "Add comment"/"Reply" or something similar would be much more straightforward for the user.

**Comment by thmo** [comment]
I think with the current version (0.1.0), this is more or less obsolete. There _is_ a button to send the suggested changes.

Nonetheless the UI is sometimes inconsistent: e.g., when you make a suggestion, move the mouse away, and then move it back, the slider ("include suggested change") automagically turns off, however the suggestion is still there and can be sent.

**Comment by JohnMcLear** [comment]
@rugk please let me know if this is still an issue, it does appear this can be closed.

https://video.etherpad.com/p/FZujg8XuXf59zEepwRIB
