### ISSUE TITLE
Long discussions are partly shown outside of the screen --> Add scrollbar inside of the comment window

### ISSUE THREAD

**Issue by rugk** [ether/ep_comments#93]
Reproduce: Just comment and reply yourself a few times. To make it longer you can also include suggestion.

What happens:
![longcomments](https://cloud.githubusercontent.com/assets/11966684/15049939/4bdec7e0-12f1-11e6-855b-6da7da28895d.png)

A scrollbar appears...

What should happen:
In long pads which already are longer than the screens height, this is not a problem, but for smaller documents it is annoying to always see a scrollbar when hovering over such a long comment.

So what should actually happen - at least for these small documents is: When hovering over the comment move the "window" up so it fits on the screen.
If the window really takes the full available height a scrollbar should appear **inside** of the comment. (So the user should be able to scroll through the comment without scrolling through the whole pad.)

_Maybe_ this behaviour is also suitable for these long documents. (I nearly assume it is.)
But one should test whether it looks nicely and is user-friendly.

**Comment by JohnMcLear** [comment]
@rugk I think this is resolved: see: https://video.etherpad.com/p/FZujg8XuXf59zEepwRIB

If not, let me know and I will re-open
