### ISSUE TITLE
Font Awesome issues (delete button not shown)

### ISSUE THREAD

**Issue by rugk** [ether/ep_comments#94]
Actually I found out the delete button needs font awesome (which is not needed by Etherpad in general as it seems). Font awesome is saved under `etherpad/static/font/fontawesome-etherpad.woff`.

However the delete button was not shown.

But from having q quick look on your code you seem to use etherpad-lite to load font awesome, so I reported the issue there: https://github.com/ether/etherpad-lite/issues/2963
So go on reading there if you're interested in this issue. (And please confirm that it must be fixed in etherpad-lite. If you can fix it, you're of course free to do it.)

**Comment by lpagliari** [comment]
The icon is part of Etherpad code. This PR added icons to it, for example: https://github.com/ether/etherpad-lite/pull/2690. On its discussion you might find a way to fix your issue too.

**Comment by rugk** [comment]
Please reopen this issue, because ep_comments seem to have an issue with that files:

Reproduce:
0. Install Etherpad with this plugin. (in a subdir)
1. Go to a pad, switch your browser console so you see loaded reuqests.
2. Filter it, so only fonts are shown.
3. Now hover over a comment.

What you'll see:
In step 2 you'll see the font being loaded:
```
200 /CustomSubDir/static/font/fontawesome-etherpad.woff
```

However when hovering over the comment another font is loaded:
```
404 /static/font/fontawesome-etherpad.woff
```

And this one can't be found in my setup.

So what happens is the following:
* All "usual" Etherpad icons are correctly shown as they use the font, which was loaded the first time.
* The small "delete" icon is broken as it tries to use the same font loaded in another (incorrect) way

This makes up two issues:
1. Why does this plugin tries to load the same font again? (And refuses to use the one, which was already loaded)
2. It loads the font incorrectly.

**Comment by JohnMcLear** [comment]
This was resolved already, sorry for not closing.
